# Generated by Django 3.1.6 on 2021-08-04 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
